### ISSUE TITLE
Enums with generics are incompatible with this macro

### ISSUE THREAD

**Issue by Jan561** [bluejekyll/enum-as-inner#18]
The following code

```rust
#[derive(EnumAsInner)]
enum Test<T> {
    A(T),
}
```
fails to compile because

```
error[E0412]: cannot find type `T` in this scope
 --> src\main.rs:5:7
  |
5 |     A(T),
  |       ^ not found in this scope

error[E0107]: wrong number of type arguments: expected 1, found 0
 --> src\main.rs:4:6
  |
4 | enum Test<T> {
  |      ^^^^ expected 1 type argument

error: aborting due to 2 previous errors

```

**Comment by bluejekyll** [comment]
That would be nice to support. I haven’t run into the need for it. I’d happily accept a PR if you are interested.

**Comment by Jan561** [comment]
I'd love to give this a shot :)

**Comment by bluejekyll** [comment]
Cool! My guess is that you need to try and extract the generic type parameters here: https://github.com/bluejekyll/enum-as-inner/blob/master/src/lib.rs#L306 

And then you'll need to pass that into the function definitions that are defined else where, like in this function: https://github.com/bluejekyll/enum-as-inner/blob/master/src/lib.rs#L295
