### ISSUE TITLE
Convert into the inner value

### ISSUE THREAD

**Issue by NeoLegends** [bluejekyll/enum-as-inner#3]
What do you think about providing accessors for converting into the inner value? Like so:

```rust
pub fn into_variant(self) -> Result<VariantType, Self> {
  match self {
    Self::Variant(x) => Ok(x),
    _ => Err(self),
  }
}
```

**Comment by bluejekyll** [comment]
This would be useful, and I think the interface you posted looks like the right way to do it.

**Comment by NeoLegends** [comment]
Think I could PR this, but I'm not familiar with proc macros (yet).
