### ISSUE TITLE
Stop using the unmaintained heck crate

### ISSUE THREAD

**Issue by jplatte** [bluejekyll/enum-as-inner#41]
[heck](https://github.com/withoutboats/heck) hasn't seen any new commits since over one and a half years and issues and pull requests haven't received any attention. It also depends on the unicode-segmentation crate, which means you probably support `#![feature(non_ascii_idents)]`, but that should not be something that's on by default IMHO.

You could instead copy the relevant parts of [serde's implementation](https://github.com/serde-rs/serde/blob/9f331cc25753edd71ad7ab0ea08a430fefaa90e1/serde_derive/src/internals/case.rs). If you don't want that, but are open to switching to a lighter implementation, I could imagine publishing and maintaining one.

**Comment by bluejekyll** [comment]
I’m not sure if I agree that there is an issue here. What problem is occurring that the heck crate is exposing?

Has the heck crate been officially marked as unmaintained?

**Comment by jplatte** [comment]
It seems excessive to pull in unicode-segmentation for what you're doing. It's not quite as heavy as some of the other unicode- crates, but still it contains way more code than this crate, and its functionality is effectively never used.

No, heck hasn't been marked unmaintained officially, but if you look at its issues and PRs (including the closed ones) you'll notice none of them have received any attention by the owner since late 2018, and that is not because nobody opened new ones or the new ones are of low quality or anything like that.

**Comment by jplatte** [comment]
The main reason I mentioned heck not being maintained is that if it was, I would look to solve the issue of pulling in unicode-normalization unconditionally upstream, but this seems impossible given the current state of affairs.

**Comment by bluejekyll** [comment]
Yes, I do notice the open issues. `heck` is currently used by quite a number of pretty common libraries out there: https://crates.io/crates/heck/reverse_dependencies

It seems reasonable to open an issue there to discuss ownership of the crate in the `heck` repo. If the current owner isn't willing to continue in that role, perhaps they'd be open to new ownership (the current owner is on the Core Rust team, so I think they would want to make sure this is in good hands and is actively maintained). Given the number of crates that depend on this crate, it seems reasonable to push for some better form of maintenance.

> It seems excessive to pull in unicode-segmentation

Is the intention here to reduce compile time? Binary size? Just trying to make sure I understand the concern here. I think that given identifiers in Rust can't be unicode, and this is only used on identifiers, it seems reasonable that that feature would be unnecessary in this context. I'd be happy to merge in a change to turn off that feature if it existed on the `heck` crate.

**Comment by jplatte** [comment]
> Is the intention here to reduce compile time? Binary size? Just trying to make sure I understand the concern here.

The former.

**Comment by bluejekyll** [comment]
Heck looks to be maintained again.

**Comment by bluejekyll** [comment]
If you think there’s something better to switch to I can. I like heck though. That you for supporting it!

**Comment by jplatte** [comment]
My memory fooled me, the version w/o mandatory unicode stuff is out as of Dec. 2021 😆 

I still haven't come across the alternative again, so I'm no longer going to annoy people to switch off heck! 🙂
