### ISSUE TITLE
Add #[inline] by default

### ISSUE THREAD

**Issue by zxch3n** [bluejekyll/enum-as-inner#86]
Because the generated functions are very small, maybe it's better to add `#[inline]` to them by default. Otherwise, we cannot use this crate in a lib efficiently

**Comment by bluejekyll** [comment]
Would you like to put up a PR?

**Comment by zxch3n** [comment]
Glad to. I made a PR

**Comment by bluejekyll** [comment]
Thank you. I’ll publish a new release.
